global_costmap:
   global_frame: world
   robot_base_frame: livox_frame
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   resolution: 0.01
   transform_tolerance: 1.0
   map_type: costmap
