obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.175, 0.175], [0.175, -0.175], [-0.175, -0.175], [-0.175, 0.175]]
#footprint_inflation: 0.01
robot_radius: 0.3
inflation_radius: 0.1
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: cloud_point
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 10}
cloud_point: {data_type: PointCloud2, topic: /livox/lidar, marking: true, clearing: true, expected_update_rate: 10}

